server:
  port: 8080

spring:
  application:
    name: SpringBoot-TCP-File-Transfer-System
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

# 文件存储配置
file-storage:
  # 可选值: local, oss, minio, tencent
  type: tencent
  local:
    upload-path: /uploads/
  oss:
    endpoint: your-oss-endpoint
    access-key-id: your-access-key-id
    access-key-secret: your-access-key-secret
    bucket-name: your-bucket-name
  minio:
    endpoint: http://your-minio-endpoint:9000
    access-key: your-minio-access-key
    secret-key: your-minio-secret-key
    bucket-name: your-minio-bucket-name
  tencent:
    secret-id:
    secret-key:
    region:
    bucket-name:

# TCP 服务配置
tcp:
  port: 9999
